// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: bcl.proto

#pragma warning disable CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace ProtoBuf.Bcl
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TimeSpan : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Value { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scale")]
        public TimeSpanScale Scale { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TimeSpanScale
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DAYS")]
            Days = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HOURS")]
            Hours = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTES")]
            Minutes = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SECONDS")]
            Seconds = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MILLISECONDS")]
            Milliseconds = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TICKS")]
            Ticks = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"MINMAX")]
            Minmax = 15,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class DateTime : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"value", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
        public long Value { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"scale")]
        public TimeSpanScale Scale { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"kind")]
        public global::System.DateTimeKind Kind { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum TimeSpanScale
        {
            [global::ProtoBuf.ProtoEnum(Name = @"DAYS")]
            Days = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HOURS")]
            Hours = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"MINUTES")]
            Minutes = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SECONDS")]
            Seconds = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MILLISECONDS")]
            Milliseconds = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TICKS")]
            Ticks = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"MINMAX")]
            Minmax = 15,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum DateTimeKind
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNSPECIFIED")]
            Unspecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"UTC")]
            Utc = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LOCAL")]
            Local = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NetObjectProxy : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int existingObjectKey { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int newObjectKey { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public int existingTypeKey { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int newTypeKey { get; set; }

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string typeName { get; set; } = "";

        [global::ProtoBuf.ProtoMember(10, Name = @"payload")]
        public byte[] Payload { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Guid : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lo", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Lo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"hi", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Hi { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Decimal : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"lo")]
        public ulong Lo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"hi")]
        public uint Hi { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint signScale { get; set; }

    }

}

#pragma warning restore CS0612, CS1591, CS3021, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
