// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: dataClass.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace JEngine.Examples
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class DataClass
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(0)]
        public int id
        {
            get { return __pbn__id ?? 0; }
            set { __pbn__id = value; }
        }
        public bool ShouldSerializeid() => __pbn__id != null;
        public void Resetid() => __pbn__id = null;
        private int? __pbn__id;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name
        {
            get { return __pbn__name ?? ""; }
            set { __pbn__name = value; }
        }
        public bool ShouldSerializename() => __pbn__name != null;
        public void Resetname() => __pbn__name = null;
        private string __pbn__name;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0)]
        public long money
        {
            get { return __pbn__money ?? 0; }
            set { __pbn__money = value; }
        }
        public bool ShouldSerializemoney() => __pbn__money != null;
        public void Resetmoney() => __pbn__money = null;
        private long? __pbn__money;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool gm
        {
            get { return __pbn__gm ?? false; }
            set { __pbn__gm = value; }
        }
        public bool ShouldSerializegm() => __pbn__gm != null;
        public void Resetgm() => __pbn__gm = null;
        private bool? __pbn__gm;

    }

}

public class ILRuntime_dataClass
{
    static ILRuntime_dataClass()
    {

        //Initlize();

    }
    public static void Initlize()
    {

        ProtoBuf.PType.RegisterType("JEngine.Examples.DataClass", typeof(JEngine.Examples.DataClass));

    }
}

#pragma warning restore CS1591, CS0612, CS3021
