// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: JEngine_Examples_DataClass.proto

#pragma warning disable CS1591, CS0612, CS3021

namespace JEngine.Examples
{
    [System.Serializable]
    [global::ProtoBuf.ProtoContract()]
    public partial class DataClass
    {
        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue(0)]
        public int id = 0;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string name = "";

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(0)]
        public long money = 0;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool gm = false;

        [global::ProtoBuf.ProtoMember(5, TypeName = "JEngine.Examples.DataClass.DataEntry")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<string, string> data = new global::System.Collections.Generic.Dictionary<string, string>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021
