name: Feature Request
description: Suggest a new feature or enhancement for JEngine
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear description of what the problem is. Ex: I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: "A clear description of what you want to happen..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: "Alternative approaches you've thought about..."
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Related Package
      description: Which JEngine package is this feature related to?
      options:
        - JEngine.Core
        - JEngine.Util
        - New Package
        - Not sure
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request.
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested before
          required: true
        - label: I would be willing to contribute this feature via a pull request
          required: false
